// ==================== DATOS DEL CATÁLOGO ====================
const individualTests = [
    { "id": "2610130002", "name": "Biometría Hemática Completa", "sample": "Sangre Total", "category": "Hematología" },
    { "id": "2610130011", "name": "Grupo Sanguíneo Y RH", "sample": "Sangre Total", "category": "Hematología" },
    { "id": "2610130018", "name": "Velocidad De Sedimentación Globular VSG", "sample": "Sangre Total", "category": "Hematología" },
    { "id": "2610130017", "name": "Conteo De Reticulocitos", "sample": "Sangre Total", "category": "Hematología" },
    { "id": "2610210038", "name": "Glucosa", "sample": "Suero", "category": "Química Clínica" },
    { "id": "2610210020", "name": "Glucosa Basal", "sample": "Suero", "category": "Química Clínica" },
    { "id": "2610210039", "name": "Glucosa Postprandial", "sample": "Suero", "category": "Química Clínica" },
    { "id": "2610210058", "name": "Urea", "sample": "Suero", "category": "Química Clínica" },
    { "id": "2610220021", "name": "Creatinina", "sample": "Suero", "category": "Química Clínica" },
    { "id": "2610210050", "name": "BUN", "sample": "Suero", "category": "Química Clínica" },
    { "id": "2610200008", "name": "Ácido Úrico", "sample": "Suero", "category": "Química Clínica" },
    { "id": "2610210059", "name": "Colesterol Total", "sample": "Suero", "category": "Química Clínica" },
    { "id": "2610210060", "name": "Colesterol HDL", "sample": "Suero", "category": "Química Clínica" },
    { "id": "2610210061", "name": "Colesterol LDL", "sample": "Suero", "category": "Química Clínica" },
    { "id": "2610210057", "name": "Triglicéridos", "sample": "Suero", "category": "Química Clínica" },
    { "id": "2610210008", "name": "Calcio", "sample": "Suero", "category": "Química Clínica" },
    { "id": "2610210055", "name": "Sodio", "sample": "Suero", "category": "Química Clínica" },
    { "id": "2610210051", "name": "Potasio", "sample": "Suero", "category": "Química Clínica" },
    { "id": "2610210010", "name": "Cloro", "sample": "Suero", "category": "Química Clínica" },
    { "id": "2610210063", "name": "Magnesio", "sample": "Suero", "category": "Química Clínica" },
    { "id": "2610210036", "name": "Fósforo", "sample": "Suero", "category": "Química Clínica" },
    { "id": "2610210002", "name": "Albúmina", "sample": "Suero", "category": "Química Clínica" },
    { "id": "2610130013", "name": "Globulina", "sample": "Suero", "category": "Química Clínica" },
    { "id": "2610210054", "name": "Proteínas Totales", "sample": "Suero", "category": "Química Clínica" },
    { "id": "2610210001", "name": "Alanina Aminotransferasa ALT", "sample": "Suero", "category": "Perfil Hepático / Enzimas" },
    { "id": "2610210004", "name": "Aspartato Aminotransferasa AST", "sample": "Suero", "category": "Perfil Hepático / Enzimas" },
    { "id": "2610210033", "name": "Fosfatasa Alcalina ALP", "sample": "Suero", "category": "Perfil Hepático / Enzimas" },
    { "id": "2610210037", "name": "Gamma‑Glutamil Transpeptidasa GGT", "sample": "Suero", "category": "Perfil Hepático / Enzimas" },
    { "id": "2610200004", "name": "Bilirrubina Total", "sample": "Suero", "category": "Perfil Hepático / Enzimas" },
    { "id": "2610210005", "name": "Bilirrubina Directa", "sample": "Suero", "category": "Perfil Hepático / Enzimas" },
    { "id": "2610200071", "name": "Bilirrubina Indirecta", "sample": "Suero", "category": "Perfil Hepático / Enzimas" },
    { "id": "2610210025", "name": "Deshidrogenasa Láctica LDH", "sample": "Suero", "category": "Perfil Hepático / Enzimas" },
    { "id": "2610210044", "name": "Índice De Resistencia A La Insulina HOMA‑IR", "sample": "Suero", "category": "Índices Calculados" },
    { "id": "2610140018", "name": "Hormona Estimulante De La Tiroides TSH", "sample": "Suero", "category": "Hormonas – Tiroides" },
    { "id": "2610140037", "name": "T3 Total", "sample": "Suero", "category": "Hormonas – Tiroides" },
    { "id": "2610140035", "name": "T3 Triyodotironina Libre", "sample": "Suero", "category": "Hormonas – Tiroides" },
    { "id": "2610140039", "name": "T4 Total", "sample": "Suero", "category": "Hormonas – Tiroides" },
    { "id": "2610140038", "name": "T4 Libre", "sample": "Suero", "category": "Hormonas – Tiroides" },
    { "id": "2610190001", "name": "Índice De Tiroxina Libre FT4I", "sample": "Suero", "category": "Hormonas – Tiroides" },
    { "id": "2610140019", "name": "FSH", "sample": "Suero", "category": "Hormonas – Ginecológicas" },
    { "id": "2610140020", "name": "LH", "sample": "Suero", "category": "Hormonas – Ginecológicas" },
    { "id": "2610140010", "name": "Estradiol", "sample": "Suero", "category": "Hormonas – Ginecológicas" },
    { "id": "2610200194", "name": "Progesterona", "sample": "Suero", "category": "Hormonas – Ginecológicas" },
    { "id": "2610140031", "name": "Prolactina", "sample": "Suero", "category": "Hormonas – Ginecológicas" },
    { "id": "2610140041", "name": "Testosterona Total", "sample": "Suero", "category": "Hormonas – Andrógenos" },
    { "id": "2610140040", "name": "Testosterona Libre", "sample": "Suero", "category": "Hormonas – Andrógenos" },
    { "id": "2610200001", "name": "17‑Alfa Hidroxiprogesterona", "sample": "Suero", "category": "Hormonas – Andrógenos" },
    { "id": "2610200023", "name": "Androstenediona", "sample": "Suero", "category": "Hormonas – Andrógenos" },
    { "id": "2610200099", "name": "Dehidroepiandrosterona DHEA", "sample": "Suero", "category": "Hormonas – Andrógenos" },
    { "id": "2610200100", "name": "Dehidroepiandrosterona Sulfato DHEAS", "sample": "Suero", "category": "Hormonas – Andrógenos" },
    { "id": "2610150141", "name": "Insulina", "sample": "Suero", "category": "Otras Hormonas" },
    { "id": "2610210014", "name": "Cortisol", "sample": "Suero", "category": "Otras Hormonas" },
    { "id": "2610210031", "name": "Ferritina", "sample": "Suero", "category": "Marcadores y Vitaminas" },
    { "id": "2610210043", "name": "Hierro", "sample": "Suero", "category": "Marcadores y Vitaminas" },
    { "id": "2610210042", "name": "Capacidad Total De Fijación De Hierro TIBC", "sample": "Suero", "category": "Marcadores y Vitaminas" },
    { "id": "2610200221", "name": "Vitamina D (25‑Hidroxi)", "sample": "Suero", "category": "Marcadores y Vitaminas" },
    { "id": "2610200219", "name": "Vitamina B12", "sample": "Suero", "category": "Marcadores y Vitaminas" },
    { "id": "2610200006", "name": "Ácido Fólico Sérico", "sample": "Suero", "category": "Marcadores y Vitaminas" },
    { "id": "2610150089", "name": "Anticuerpos Antinucleares ANA", "sample": "Suero", "category": "Inmunología / Autoinmunidad" },
    { "id": "2610150037", "name": "Anti‑DNA De Doble Cadena", "sample": "Suero", "category": "Inmunología / Autoinmunidad" },
    { "id": "2610140028", "name": "Anticuerpos Anti‑CCP", "sample": "Suero", "category": "Inmunología / Autoinmunidad" },
    { "id": "2610200266", "name": "Anticuerpo Anti Peroxidasa Tiroidea TPO", "sample": "Suero", "category": "Inmunología / Autoinmunidad" },
    { "id": "2610150103", "name": "Anticuerpos Anti Tiroglobulina TG", "sample": "Suero", "category": "Inmunología / Autoinmunidad" },
    { "id": "2610150091", "name": "Anticuerpos Anti‑Receptor TSH TRAb", "sample": "Suero", "category": "Inmunología / Autoinmunidad" },
    { "id": "2610150085", "name": "Anticuerpos Anti‑Mitocondriales AMA", "sample": "Suero", "category": "Inmunología / Autoinmunidad" },
    { "id": "2610150086", "name": "Anticuerpos Anti‑Músculo Liso ASMA", "sample": "Suero", "category": "Inmunología / Autoinmunidad" },
    { "id": "2610150035", "name": "Anticuerpos P‑ANCA Y C‑ANCA", "sample": "Suero", "category": "Inmunología / Autoinmunidad" },
    { "id": "2610150023", "name": "Anticuerpos Anticardiolipinas IgG/IgM", "sample": "Suero", "category": "Inmunología / Autoinmunidad" },
    { "id": "2610150051", "name": "Anticuerpos Anti‑β2‑Glicoproteína IgG", "sample": "Suero", "category": "Inmunología / Autoinmunidad" },
    { "id": "2610200060", "name": "Anticuerpos Anti‑β2‑Glicoproteína IgM", "sample": "Suero", "category": "Inmunología / Autoinmunidad" },
    { "id": "2610150112", "name": "VIH Presuntivo", "sample": "Suero", "category": "Serología y Pruebas Rápidas" },
    { "id": "2610150154", "name": "VDRL Presuntivo Sífilis", "sample": "Suero", "category": "Serología y Pruebas Rápidas" },
    { "id": null, "name": "Hepatitis B Prueba Rápida", "sample": "Suero", "category": "Serología y Pruebas Rápidas" },
    { "id": "2610150062", "name": "Hepatitis C Prueba Rápida", "sample": "Suero", "category": "Serología y Pruebas Rápidas" },
    { "id": "2610150145", "name": "PCR Látex Proteína C Reactiva", "sample": "Suero", "category": "Serología y Pruebas Rápidas" },
    { "id": "2610150123", "name": "Antiestreptolisinas ASO", "sample": "Suero", "category": "Serología y Pruebas Rápidas" },
    { "id": "2610150139", "name": "Factor Reumatoide FR Látex", "sample": "Suero", "category": "Serología y Pruebas Rápidas" },
    { "id": "2610150148", "name": "Reacciones Febriles", "sample": "Suero", "category": "Serología y Pruebas Rápidas" },
    { "id": "2610150150", "name": "Rosa De Bengala", "sample": "Suero", "category": "Serología y Pruebas Rápidas" },
    { "id": "2610190106", "name": "Prueba Rápida De COVID / Influenza A‑B", "sample": "Suero", "category": "Serología y Pruebas Rápidas" },
    { "id": "2610110025", "name": "Tiempo De Protrombina TP", "sample": "Plasma", "category": "Coagulación / Hemostasia" },
    { "id": "2610110026", "name": "INR", "sample": "Plasma", "category": "Coagulación / Hemostasia" },
    { "id": "2610110024", "name": "Tiempo De Tromboplastina Parcial Activada TPTa", "sample": "Plasma", "category": "Coagulación / Hemostasia" },
    { "id": "2610110023", "name": "Tiempo De Trombina TT", "sample": "Plasma", "category": "Coagulación / Hemostasia" },
    { "id": "2610110016", "name": "Fibrinógeno", "sample": "Plasma", "category": "Coagulación / Hemostasia" },
    { "id": "2610220034", "name": "Examen General De Orina", "sample": "Orina", "category": "Urianálisis" },
    { "id": "2610100061", "name": "Urocultivo", "sample": "Orina", "category": "Microbiología" },
    { "id": "2610100044", "name": "Hemocultivo Aerobio", "sample": "Sangre", "category": "Microbiología" },
    { "id": "2610100044", "name": "Hemocultivo Anaerobio", "sample": "Sangre", "category": "Microbiología" },
    { "id": "2610100016", "name": "Cultivo De Exudado Faríngeo", "sample": "Exudado Faríngeo", "category": "Microbiología" },
    { "id": "2610100039", "name": "Cultivo De Exudado Vaginal", "sample": "Exudado Vaginal", "category": "Microbiología" },
    { "id": "2610100037", "name": "Cultivo De Exudado Uretral", "sample": "Exudado Uretral", "category": "Microbiología" },
    { "id": "2610100018", "name": "Cultivo De Exudado De Herida / Absceso", "sample": "Exudado de Herida", "category": "Microbiología" },
    { "id": "2610100026", "name": "Cultivo De Hongos", "sample": "Variable", "category": "Microbiología" },
    { "id": "2610100024", "name": "Cultivo De Esputo", "sample": "Esputo", "category": "Microbiología" },
    { "id": "2610100042", "name": "Cultivo De Semen (Espermocultivo)", "sample": "Semen", "category": "Microbiología" },
    { "id": "2610100023", "name": "Cultivo De Punta De Catéter", "sample": "Punta de Catéter", "category": "Microbiología" },
    { "id": "2610100040", "name": "Cultivo De Exudado Nasal", "sample": "Exudado Nasal", "category": "Microbiología" },
    { "id": "2610100035", "name": "Cultivo De Secreción Ótica", "sample": "Exudado Ótico", "category": "Microbiología" },
    { "id": "2610100024", "name": "Cultivo De Secreción Bronquial", "sample": "Secreción Bronquial", "category": "Microbiología" },
    { "id": "2610180018", "name": "Coprocultivo", "sample": "Heces", "category": "Microbiología" },
    { "id": "2610100020", "name": "Cultivo De Líquido Pleural", "sample": "Líquido Pleural", "category": "Microbiología" },
    { "id": "2610100020", "name": "Cultivo De Líquido Sinovial", "sample": "Líquido Sinovial", "category": "Microbiología" },
    { "id": "2610100020", "name": "Cultivo De Líquido Cefaloraquídeo", "sample": "Líquido Cefalorraquídeo", "category": "Microbiología" },
    { "id": "2610100020", "name": "Cultivo De Líquidos Corporales", "sample": "Líquido Corporal", "category": "Microbiología" },
    { "id": "2610180009", "name": "Coproparasitoscópico 1 Muestra", "sample": "Heces", "category": "Parasitología" },
    { "id": "2610180010", "name": "Coproparasitoscópico 2 Muestras", "sample": "Heces", "category": "Parasitología" },
    { "id": "2610180011", "name": "Coproparasitoscópico 3 Muestras", "sample": "Heces", "category": "Parasitología" },
    { "id": "2610180008", "name": "Coprológico", "sample": "Heces", "category": "Parasitología" },
    { "id": "2610180005", "name": "Prueba De Azúcares Reductores", "sample": "Heces u Orina", "category": "Parasitología" },
    { "id": "2610180016", "name": "Sangre Oculta En Heces", "sample": "Heces", "category": "Parasitología" },
    { "id": "2610180002", "name": "Amiba En Fresco", "sample": "Heces", "category": "Parasitología" },
    { "id": "2610100045", "name": "Examen De Gota Gruesa", "sample": "Sangre Total", "category": "Parasitología" },
    { "id": "2610160004", "name": "Citoquímico De Líquido Cefalorraquídeo", "sample": "Líquido Cefalorraquídeo", "category": "Líquidos Corporales (Citoquímicos)" },
    { "id": "2610160005", "name": "Citoquímico De Líquido Pleural", "sample": "Líquido Pleural", "category": "Líquidos Corporales (Citoquímicos)" },
    { "id": "2610160006", "name": "Citoquímico De Líquido Sinovial", "sample": "Líquido Sinovial", "category": "Líquidos Corporales (Citoquímicos)" },
    { "id": "2610160007", "name": "Citoquímico De Líquido Bronquial", "sample": "Líquido Bronquial", "category": "Líquidos Corporales (Citoquímicos)" },
    { "id": "2610160001", "name": "Citoquímico De Líquido De Ascitis O Peritoneal", "sample": "Líquido de Ascitis", "category": "Líquidos Corporales (Citoquímicos)" },
    { "id": "2610160002", "name": "Citoquímico De Líquido De Diálisis", "sample": "Líquido de Diálisis", "category": "Líquidos Corporales (Citoquímicos)" },
    { "id": "2610160007", "name": "Citoquímico De Líquido Orgánicos Varios", "sample": "Líquido Corporal", "category": "Líquidos Corporales (Citoquímicos)" },
    { "id": "2610200227", "name": "Tamiz Neonatal Ampliado", "sample": "Sangre Capilar", "category": "Tamizaje" }
];

const packages = [
    { "id": "2010110369", "name": "Check Up Qs 6 Elementos", "tests": ["Biometría Hemática Completa", "Glucosa", "Urea", "Creatinina", "Colesterol Total", "Triglicéridos"] },
    { "id": "2010110370", "name": "Check Up Qs 15 Elementos", "tests": ["Biometría Hemática Completa", "Glucosa", "Urea", "Creatinina", "Ácido Úrico", "Colesterol Total", "Colesterol HDL", "Colesterol LDL", "Triglicéridos", "Alanina Aminotransferasa ALT", "Aspartato Aminotransferasa AST", "Fosfatasa Alcalina ALP", "Bilirrubina Total", "Proteínas Totales", "Examen General De Orina"] },
    { "id": "2010110371", "name": "Check Up Qs 35 Elementos", "tests": ["Biometría Hemática Completa", "Glucosa", "Urea", "Creatinina", "BUN", "Ácido Úrico", "Colesterol Total", "Colesterol HDL", "Colesterol LDL", "Colesterol VLDL", "Triglicéridos", "Índice Aterogénico", "Relación LDL/HDL", "Alanina Aminotransferasa ALT", "Aspartato Aminotransferasa AST", "Fosfatasa Alcalina ALP", "Gamma‑Glutamil Transpeptidasa GGT", "Bilirrubina Total", "Bilirrubina Directa", "Bilirrubina Indirecta", "Proteínas Totales", "Albúmina", "Globulina", "Relación Albúmina/Globulina", "Sodio", "Potasio", "Cloro", "Calcio", "Fósforo", "Magnesio", "Examen General De Orina"] },
    { "id": "2610190053", "name": "Química Sanguínea 3 Elementos", "tests": ["Glucosa", "Urea", "Creatinina"] },
    { "id": "2610190058", "name": "Química Sanguínea 6 Elementos", "tests": ["Glucosa", "Urea", "Creatinina", "Ácido Úrico", "Colesterol Total", "Triglicéridos"] },
    { "id": null, "name": "Química Sanguínea 15 Elementos", "tests": ["Glucosa", "Urea", "Creatinina", "Ácido Úrico", "Colesterol Total", "Triglicéridos", "Aspartato Aminotransferasa AST", "Alanina Aminotransferasa ALT", "Fosfatasa Alcalina ALP", "Gamma‑Glutamil Transpeptidasa GGT", "Bilirrubina Total", "Proteínas Totales", "Sodio", "Potasio", "Cloro"] },
    { "id": "2610190064", "name": "Química Sanguínea 27 Elementos", "tests": ["Glucosa", "Urea", "Creatinina", "BUN", "Ácido Úrico", "Sodio", "Potasio", "Cloro", "Magnesio", "Calcio", "Fósforo", "Albúmina", "Aspartato Aminotransferasa AST", "Alanina Aminotransferasa ALT", "Bilirrubina Directa", "Bilirrubina Indirecta", "Bilirrubina Total", "Deshidrogenasa Láctica LDH", "Fosfatasa Alcalina ALP", "Gamma‑Glutamil Transpeptidasa GGT", "Globulina", "Proteínas Totales", "Relación Albúmina/Globulina", "Colesterol HDL", "Colesterol LDL", "Colesterol Total", "Triglicéridos"] },
    { "id": "2610190078", "name": "Química Sanguínea 35 Elementos", "tests": ["Glucosa", "Urea", "Creatinina", "BUN", "Ácido Úrico", "Colesterol Total", "Colesterol HDL", "Colesterol LDL", "Colesterol VLDL", "Triglicéridos", "Aspartato Aminotransferasa AST", "Alanina Aminotransferasa ALT", "Fosfatasa Alcalina ALP", "Gamma‑Glutamil Transpeptidasa GGT", "Bilirrubina Total", "Bilirrubina Directa", "Bilirrubina Indirecta", "Albúmina", "Globulina", "Proteínas Totales", "Sodio", "Potasio", "Cloro", "Calcio", "Fósforo", "Magnesio", "Amilasa", "Lipasa", "CPK Creatina Fosfocinasa Total", "Deshidrogenasa Láctica LDH", "Hierro", "Índice Aterogénico", "Relación BUN/Creatinina", "Relación Albúmina/Globulina", "Relación LDL/HDL"] },
    { "id": "2610210027", "name": "Electrolitos Séricos De 3", "tests": ["Sodio", "Potasio", "Cloro"] },
    { "id": "2610210030", "name": "Electrolitos Séricos De 6", "tests": ["Sodio", "Potasio", "Cloro", "Calcio", "Magnesio", "Fósforo"] },
    { "id": "2610190053", "name": "Perfil De Lípidos", "tests": ["Colesterol Total", "Colesterol HDL", "Colesterol LDL", "Colesterol VLDL", "Triglicéridos", "Índice Aterogénico", "Relación LDL/HDL"] },
    { "id": "2610190025", "name": "Perfil Hepático", "tests": ["Albúmina", "Alanina Aminotransferasa ALT", "Aspartato Aminotransferasa AST", "Bilirrubina Directa", "Bilirrubina Indirecta", "Bilirrubina Total", "Deshidrogenasa Láctica LDH", "Fosfatasa Alcalina ALP", "Gamma‑Glutamil Transpeptidasa GGT", "Globulina", "Proteínas Totales", "Relación Albúmina/Globulina"] },
    { "id": "2610190111", "name": "Perfil De Hierro", "tests": ["Hierro", "Ferritina", "Capacidad Latente De Fijación De Hierro UIBC", "Capacidad Total De Fijación De Hierro TIBC", "Porcentaje De Saturación De Transferrina"] },
    { "id": "2610190045", "name": "Perfil Tiroideo", "tests": ["Hormona Estimulante De La Tiroides TSH", "T3 Total", "T3 Triyodotironina Libre", "T4 Total", "T4 Libre", "Índice De Fijación De Tiroxina IFT", "Índice De Tiroxina Libre FT4I"] },
    { "id": "2610190024", "name": "Perfil Ginecológico", "tests": ["FSH", "LH", "Estradiol", "Progesterona", "Prolactina", "Testosterona Total"] },
    { "id": "2610190005", "name": "Perfil De Andrógenos", "tests": ["17‑Alfa Hidroxiprogesterona", "Androstenediona", "Dehidroepiandrosterona DHEA", "Dehidroepiandrosterona Sulfato DHEAS", "Testosterona Libre Y Total"] },
    { "id": "2610190040", "name": "Perfil Reumático", "tests": ["Proteína C Reactiva PCR Cuantitativa", "Ácido Úrico", "Factor Reumatoide FR", "Velocidad De Sedimentación Globular VSG", "Biometría Hemática Completa", "Antiestreptolisinas ASO"] },
    { "id": null, "name": "Perfil Control De Diabetes", "tests": ["Glucosa", "Hemoglobina Glicosilada", "Examen General De Orina"] },
    { "id": "2610210020", "name": "Curva De Tolerancia De Glucosa 2 H", "tests": ["Glucosa Basal", "Glucosa 1h", "Glucosa 2 h"] },
    { "id": "2610210022", "name": "Curva De Tolerancia De Glucosa 3 H", "tests": ["Glucosa Basal", "Glucosa 1h", "Glucosa 2 h", "Glucosa 3 h"] },
    { "id": "2610190112", "name": "Enzimas Pancreáticas", "tests": ["Amilasa", "Lipasa"] },
    { "id": "2610190112", "name": "Preoperatorios", "tests": ["Biometría Hemática Completa", "Glucosa", "Urea", "Creatinina", "Grupo Sanguíneo Y RH", "Tiempo De Protrombina TP", "Tiempo De Tromboplastina Parcial Activada TPTa", "INR"] },
    { "id": "2610200266", "name": "Anticuerpos Anti Tiroideos", "tests": ["Anticuerpo Anti Peroxidasa Tiroidea TPO", "Anticuerpos Anti Tiroglobulina TG"] },
    { "id": "2610190011", "name": "Antidoping De 3", "tests": ["Anfetaminas", "Cocaína", "Tetrahidrocanabinoides"] },
    { "id": "2610190011", "name": "Antidoping De 5", "tests": ["Anfetaminas", "Benzodiacepinas", "Cocaína", "Metanfetaminas", "Tetrahidrocanabinoides"] },
    { "id": "2610200227", "name": "Tamiz Neonatal Ampliado", "tests": ["Tamiz Neonatal Ampliado"] }
];